# Generated by Django 5.2.7 on 2025-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_nombre', models.CharField(db_index=True, max_length=120, unique=True)),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('ciclos', 'Por ciclos/uso')], db_index=True, max_length=20)),
                ('plan_tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('predictivo', 'Predictivo'), ('correctivo', 'Correctivo'), ('inspeccion', 'Inspección')], db_index=True, max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plan de gestión',
                'verbose_name_plural': 'Planes de gestión',
                'indexes': [models.Index(fields=['plan_tipo'], name='plan_gestio_plan_ti_750956_idx'), models.Index(fields=['frecuencia'], name='plan_gestio_frecuen_972b04_idx')],
            },
        ),
    ]
