# Generated by Django 5.2.7 on 2025-11-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plangestion',
            name='estado',
            field=models.CharField(choices=[('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado')], default='habilitado', max_length=20),
        ),
    ]
