# Generated by Django 5.2.7 on 2025-11-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        ('plan_gestion', '0002_plangestion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plangestion',
            name='activo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planes_activos', to='activos.activo'),
            preserve_default=False,
        ),
    ]
