# Generated by Django 5.2.8 on 2025-12-04 19:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0004_ordentrabajo_encuesta_ordentrabajo_tecnico_asignado_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Tecnico', 'Tecnico'), ('Operario', 'Operario')], default='Operario', max_length=50),
        ),
        migrations.CreateModel(
            name='User_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.CharField(choices=[('1', 'Muy insatisfecho'), ('2', 'Insatisfecho'), ('3', 'Indiferente'), ('4', 'Satisfecho'), ('5', 'Muy satisfecho')], db_index=True, default='5', max_length=15)),
                ('comentario', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('OT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Orden_trabajo', to='orden_trabajo.ordentrabajo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
