# Generated by Django 5.2.8 on 2025-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_cargo_cargo_user_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_feedback',
            old_name='OT',
            new_name='orden_trabajo',
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='calificacion',
            field=models.CharField(choices=[('1', 'Muy insatisfecho'), ('2', 'Insatisfecho'), ('3', 'Indiferente'), ('4', 'Satisfecho'), ('5', 'Muy satisfecho')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='comentario',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
