# Generated by Django 5.2.7 on 2025-11-22 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('plan_gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_falla', models.TextField()),
                ('acciones', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('OT_estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_ejecucion', 'En ejecución'), ('cerrada', 'Cerrada'), ('bloqueada', 'Bloqueada')], db_index=True, default='abierta', max_length=15)),
                ('recursos_usados', models.JSONField(blank=True, default=dict)),
                ('tiempo_intervencion', models.DurationField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activo_ordenes', to='activos.activo')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_ordenes', to='plan_gestion.plangestion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['OT_estado'], name='orden_traba_OT_esta_d34153_idx'), models.Index(fields=['activo', 'OT_estado'], name='orden_traba_activo__18239a_idx'), models.Index(fields=['plan'], name='orden_traba_plan_id_265fe5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio')), ('fecha_fin__isnull', True), _connector='OR'), name='ck_wo_end_after_start')],
            },
        ),
    ]
