# Generated by Django 5.2.7 on 2025-11-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='codigo',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='recursos_usados',
            field=models.TextField(blank=True),
        ),
    ]
