# Generated by Django 5.2.8 on 2025-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0005_alter_ordentrabajo_encuesta_notificacionot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='descripcion_falla',
            field=models.TextField(max_length=200),
        ),
    ]
