# Generated by Django 5.2.7 on 2025-11-22 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('orden_trabajo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('nivel_prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], db_index=True, max_length=10)),
                ('estado', models.CharField(choices=[('reportada', 'Reportada'), ('en_proceso', 'En proceso'), ('resuelta', 'Resuelta'), ('cancelada', 'Cancelada')], db_index=True, default='reportada', max_length=12)),
                ('OT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='OT_incidencia', to='orden_trabajo.ordentrabajo')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activo_incidencias', to='activos.activo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_reporte'],
                'indexes': [models.Index(fields=['nivel_prioridad'], name='incidencia__nivel_p_3956b2_idx'), models.Index(fields=['estado'], name='incidencia__estado_6235b5_idx'), models.Index(fields=['activo', 'estado'], name='incidencia__activo__464642_idx')],
            },
        ),
    ]
