# Generated by Django 5.2.7 on 2025-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(db_index=True, max_length=60)),
                ('ubicacion', models.CharField(db_index=True, max_length=120)),
                ('estado_operativo', models.CharField(choices=[('operativo', 'Operativo'), ('inoperativo', 'Inoperativo'), ('mantenimiento', 'En mantenimiento'), ('retirado', 'Retirado')], db_index=True, default='operativo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'indexes': [models.Index(fields=['tipo'], name='activos_act_tipo_422937_idx'), models.Index(fields=['ubicacion'], name='activos_act_ubicaci_e6ad25_idx'), models.Index(fields=['estado_operativo'], name='activos_act_estado__6639c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('codigo',), name='uq_activo_codigo')],
            },
        ),
    ]
