# Generated by Django 5.2.8 on 2025-12-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tipo',
            field=models.CharField(choices=[('M/CNCC', 'Maquinaria de Mecanizado CNC y Convencional'), ('M/CE', 'Maquinaria de Conformado y Estampado'), ('E/SCT', 'Equipo de Soldadura y Corte Térmico'), ('E/ASS', 'Equipos Auxiliares y Sistemas de Soporte'), ('E/IMC', 'Equipos de Izaje y Movimiento de Carga'), ('E/MP', 'Herramientas y Equipos de Medición/Prueba'), ('I/ES', 'Instalaciones Eléctricas y Servicios')], db_index=True, max_length=20),
        ),
    ]
