# Generated by Django 5.2.7 on 2025-11-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField()),
                ('mmt_tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('predictivo', 'Predictivo'), ('correctivo', 'Correctivo'), ('inspeccion', 'Inspección')], db_index=True, max_length=20)),
                ('detalle_evento', models.TextField()),
                ('responsable', models.CharField(max_length=120)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo_historial', to='activos.activo')),
            ],
            options={
                'verbose_name': 'Historial de gestión',
                'verbose_name_plural': 'Historiales de gestión',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['mmt_tipo', 'fecha_evento'], name='historial_h_mmt_tip_2461a4_idx'), models.Index(fields=['activo', 'fecha_evento'], name='historial_h_activo__73bd09_idx')],
            },
        ),
    ]
