# Generated by Django 5.2.7 on 2025-11-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialgestion',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activo_historial', to='activos.activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historialgestion',
            name='detalle_evento',
            field=models.TextField(verbose_name='Detalle del evento'),
        ),
        migrations.AlterField(
            model_name='historialgestion',
            name='fecha_evento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historialgestion',
            name='mmt_tipo',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('predictivo', 'Predictivo'), ('correctivo', 'Correctivo'), ('inspeccion', 'Inspección')], db_index=True, max_length=20, verbose_name='Tipo de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='historialgestion',
            name='responsable',
            field=models.CharField(max_length=120, verbose_name='Responsable'),
        ),
    ]
