# Generated by Django 5.2.7 on 2025-11-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_alter_historialgestion_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialgestion',
            name='referencia_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
