# Generated by Django 5.2.7 on 2025-11-26 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_historialgestion_referencia_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialgestion',
            name='responsable',
        ),
        migrations.AddField(
            model_name='historialgestion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
